name: Deployment

on:
  push:
    branches:
      - main

jobs:
  coverage-report:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.0
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry export --with dev > requirements.txt
        pip install -r requirements.txt
        pip install -e .
    - name: Run tests
      run: |
        pytest --cov-report lcov
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./coverage.lcov
